import { TransactionType } from '../../shared/types/type';

export const mockTransactions: TransactionType[] = [
  {
    id: 'txn-001',
    name: 'Lunch at cafe',
    invoice: null,
    amount: 120000,
    expenseDate: new Date('2025-07-20'),
    // weekNumber: 29,
    isRecurring: false,
    expenseCategory: 'Food',
    payment: 'Cash',
    comment: 'Had lunch with colleagues',
    location: 'District 1, HCM',
  },
  {
    id: 'txn-002',
    name: 'Monthly Internet Bill',
    invoice: null,
    amount: 250000,
    expenseDate: new Date('2025-07-01'),
    // weekNumber: 27,
    isRecurring: true,
    expenseCategory: 'Utilities',
    payment: 'Bank Transfer',
    comment: 'VNPT payment',
    location: 'Home',
  },
  {
    id: 'txn-003',
    name: 'Grab ride to work',
    invoice: null,
    amount: 75000,
    expenseDate: new Date('2025-07-22'),
    // weekNumber: 30,
    isRecurring: true,
    expenseCategory: 'Transportation',
    payment: 'E-Wallet',
    comment: 'Paid via Momo',
    location: 'Go Vap, HCM',
  },
  {
    id: 'txn-004',
    name: 'Movie ticket',
    invoice: null,
    amount: 90000,
    expenseDate: new Date('2025-07-18'),
    // weekNumber: 29,
    isRecurring: false,
    expenseCategory: 'Entertainment',
    payment: 'Credit Card',
    comment: 'Weekend movie',
    location: 'CGV Crescent Mall',
  },
  {
    id: 'txn-005',
    name: 'Medicine purchase',
    invoice: null,
    amount: 180000,
    expenseDate: new Date('2025-07-15'),
    // weekNumber: 29,
    isRecurring: false,
    expenseCategory: 'Healthcare',
    payment: 'Cash',
    comment: 'Bought painkillers',
    location: 'Pharmacy - Nguyen Thi Minh Khai',
  },
  {
    id: 'txn-006',
    name: 'Online course fee',
    invoice: null,
    amount: 400000,
    expenseDate: new Date('2025-07-10'),
    // weekNumber: 28,
    isRecurring: false,
    expenseCategory: 'Education',
    payment: 'Bank Transfer',
    comment: 'Udemy course on TypeScript',
    location: 'Online',
  },
];

export const cities = [
  { name: 'New York', code: 'NY' },
  { name: 'Rome', code: 'RM' },
  { name: 'London', code: 'LDN' },
  { name: 'Istanbul', code: 'IST' },
  { name: 'Paris', code: 'PRS' },
];
export const expenseCategories = ['Shopping', 'Food', 'Drink'];
